server:
  port: 8089
  
spring:
  application:
    name: account-service

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8888}/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2