version: 0.2

phases:
  post_build:
    commands:
      - cd week4/LeagueOfLegendsApi && mvn clean package
artifacts:
  files:
    - '**/*'
  base-directory: 'week4/LeagueOfLegendsApi/target/LeagueOfLegendsApi'
